### ISSUE TITLE
Fix Icon font generation

### ISSUE THREAD

**Issue by tdurand** [usebedrock/bedrock#203]
Seems to be broken, some discussion here: https://github.com/usebedrock/bedrock/pull/198

cc @Wolfr

**Comment by Wolfr** [comment]
I can confirm it also occurs in older versions like 1.7.3.

Some more background in this reply:

* The gulp task generates some temporary folders which don't get deleted or cleaned up so if the icon font worked {on your computer} at some point in time, you don't see that the generation is broken unless you add a new icon, and even then, sometimes just the display of the new icon might be broken.

* To reproduce a “clean” Bedrock situation @xavez had a trick I think - @xavez can you share your git clean command?

* In general, we have struggled with the icon font for a while. We have it working in several instances of Bedrock that we are using but it's always been a hassle for people to get up and running.

* It uses Ruby as a dependency, which is why we have the Gemfile; https://github.com/usebedrock/bedrock/blob/master/Gemfile .

* Recently I also had to change something to address a security issue as well as support woff2 - https://bedrock.mono.company/2018/04/29/icon-fonts-bedrock-1-6/ .

**Comment by xavez** [comment]
It’s `git clean -fd` https://git-scm.com/docs/git-clean/2.2.0

**Comment by tdurand** [comment]
Ok, will debug this along with other issues you linked me, I can reproduce the bug so I have a clean install 😉

**Comment by tdurand** [comment]
It actually works, but a few things were misleading: first I didn't find easily the install instruction here: https://github.com/usebedrock/bedrock#using-icon-fonts , I came myself to the conclusion seeing in the code that I needed to install the fontcustom command line tool

I think this should appear on the website, maybe it is already but didn't found it 😁

Also those instructions could use a little bit more information, so I sended a PR to improve them a bit

As iconfont are getting a bit old fashioned and have many drawback, we may not work to improve their support with bedrock, but if we want we may consider to remove this external ruby gem dependency to go with a node.js based font generator that would get installed directly with all other dependencies so the set-up is less of a pain for the end-user. I didn't test but seems there are such packages out there: https://github.com/Workshape/icon-font-generator

**Comment by Wolfr** [comment]
**nodejs based solution**

I think moving to a nodejs based solution could be explored, but we have tried this before, and we had problems to get it working whereas fontcustom works very well once you have it set up.

**Icon fonts - general - why do we still use it?**

While it is a pain we still see many advantages in icon fonts. The reason lies mostly in performance. Consider a list with 1000 chat items where within each chat item there are 10 icons. Inline SVG just generated a crazy amount of markup whereas icon fonts do not.

**PR***

I commented on the PR itself.

**Comment by tdurand** [comment]
- Yes I have no idea how good are node.js based icon font generator / how painfull they are to work with, it's not that are to install fontcustom for people that want to work with generating their own iconfont, which is an "expert" usecase anyway

- I agree with you, icon font are still a great technical solution for front-end dev 😉
